### ISSUE TITLE
/sell all

### ISSUE THREAD

**Issue by ShadowGamer100** [AndreasHGK/SellAll#1]
They issue broken only /sell all we cant sell item is something wrong with code $item = $sender->getInventory()->getItemInHand(); becuase is only hand on sell all commands

**Comment by andreashgk** [comment]
what? I don't get you. If there's an error in the console, could you please paste it in here?

**Comment by ShadowGamer100** [comment]
you should test when i give stone then i sell /sell all is said you cant sell item they already have config

**Comment by andreashgk** [comment]
for me it works perfectly fine. Could you maybe record a video and send it? Also, did you check if you didn't accidently changed something in the config. When you change the config you also have to reload the server for the changes to happen
