### ISSUE TITLE
Set Price for specific type/colour of blocks.

### ISSUE THREAD

**Issue by ver24436** [AndreasHGK/SellAll#4]
If I wanted to set a specific color of stained glass for example, to have a different price how would I set this in the config file.

From what I can tell we can't set for example  

241:4 35 # Yellow Stained Glass $35
241:1 120 # Orange Stained Glass $120

It seems to only accept the first number of the ID.  It'd be nice to have the flexibility to set different prices for blocks of the same type but different colors. This is not limited to the stained glass example and can apply to a variety of blocks that use a secondary number to identify the block.

The other advantage would be when someone went to use /sell all  while they had the Yellow Stained Glass in hand.. rather then it selling all stained glass it'd sell just the stacks of that specific color.

**Comment by andreashgk** [comment]
sorry for the wait, but i have now implemented this.

**Comment by ver24436** [comment]
Thanks!
